root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/app ./cmd/server"
bin = "./tmp/app"
include_ext = ["go"]
exclude_dir = ["tmp", "gen", "vendor"]
delay = 200
log_color = "true"
stop_on_error = false

[log]
time = true

[color]
app = "cyan"
build = "yellow"
watcher = "magenta"
main = "green"
runner = "blue"