package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/CutyDog/mint-flea/services/gateway/graph/model"
)

// LinkWallet is the resolver for the LinkWallet field.
func (r *mutationResolver) LinkWallet(ctx context.Context, input model.LinkWalletInput) (*model.Wallet, error) {
	panic(fmt.Errorf("not implemented: LinkWallet - LinkWallet"))
}

// UnlinkWallet is the resolver for the UnlinkWallet field.
func (r *mutationResolver) UnlinkWallet(ctx context.Context, input model.UnlinkWalletInput) (bool, error) {
	panic(fmt.Errorf("not implemented: UnlinkWallet - UnlinkWallet"))
}

// SetMainWallet is the resolver for the SetMainWallet field.
func (r *mutationResolver) SetMainWallet(ctx context.Context, input model.SetMainWalletInput) (*model.Wallet, error) {
	panic(fmt.Errorf("not implemented: SetMainWallet - SetMainWallet"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
