package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"log"

	"github.com/CutyDog/mint-flea/services/gateway/auth"
	"github.com/CutyDog/mint-flea/services/gateway/graph/model"
)

func (r *queryResolver) Me(ctx context.Context) (*model.Account, error) {
	uid, err := auth.GetUserUIDFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get user UID: %w", err)
	}

	// Get account from gRPC service
	account, err := r.AccountClient.GetAccountByUID(ctx, uid)
	log.Printf("account: %+v", account)
	if err != nil {
		return nil, fmt.Errorf("failed to get account: %w", err)
	}

	// Check if account is nil
	if account == nil {
		return nil, fmt.Errorf("account not found")
	}

	// Convert protobuf to GraphQL model
	return &model.Account{
		ID:        fmt.Sprintf("%d", account.Id),
		UID:       account.Uid,
		CreatedAt: account.CreatedAt.AsTime().Format("2006-01-02T15:04:05Z07:00"),
		UpdatedAt: account.UpdatedAt.AsTime().Format("2006-01-02T15:04:05Z07:00"),
	}, nil
}

// Account is the resolver for the account field.
func (r *queryResolver) Account(ctx context.Context, uid string) (*model.Account, error) {
	// Get account from gRPC service
	account, err := r.AccountClient.GetAccountByUID(ctx, uid)
	if err != nil {
		return nil, fmt.Errorf("failed to get account: %w", err)
	}

	// Check if account is nil
	if account == nil {
		return nil, fmt.Errorf("account not found")
	}

	// Convert protobuf to GraphQL model
	return &model.Account{
		ID:        fmt.Sprintf("%d", account.Id),
		UID:       account.Uid,
		CreatedAt: account.CreatedAt.AsTime().Format("2006-01-02T15:04:05Z07:00"),
		UpdatedAt: account.UpdatedAt.AsTime().Format("2006-01-02T15:04:05Z07:00"),
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
